# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hansode/centos-6.6-x86_64"
  config.vm.synced_folder "./", "/home/vagrant/shared"
  config.vm.synced_folder "../", "/home/vagrant/ducttape"
  config.ssh.insert_key = false

  config.vm.define "server" do |node|
    node.vm.provider :virtualbox do |v, override|
       node.vm.network :private_network, ip: "192.168.56.10", :adapter => 2, virtualbox__intnet: "name"
    end
  end

  config.vm.define "client-1" do |node|
    node.vm.provider :virtualbox do |v, override|
      node.vm.network :private_network, ip: "192.168.56.100", :adapter => 2, virtualbox__intnet: "name"
    end
  end

end
